#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#=================================
# global settings
#=================================
# 默认的窗口布局(float, bsp)
yabai -m config layout                       float
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
# floating windows are always on top
yabai -m config window_topmost               on
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config window_border                off
yabai -m config window_border_width          4
# yabai -m config active_window_border_color   0xff7aa2f7
# yabai -m config normal_window_border_color   0xff444b6a
# yabai -m config active_window_border_color   0xff81A1C1
# yabai -m config normal_window_border_color   0xff7A808C

yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10


# Override default layout for space 2 only
yabai -m config --space 2 layout float

# float preferences
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^系统偏好" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^访达$" sticky=on layer=above manage=off
yabai -m rule --add app="^Calendar" manage=off
yabai -m rule --add app="^日历" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^预览$" manage=off
yabai -m rule --add app="^网易" manage=off
yabai -m rule --add app="^微信" manage=off
yabai -m rule --add title="^Opening .*$" manage=off layer=above
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off

echo "yabai configuration loaded.."
